Adding axe, axe-beta and axe-con
a11yproject/a11yproject.com pull request #1098
Opened 2020-09-01 19:09 UTC by ljgoslin

First time adding changes to this doc, hopefully, I did it right - thanks all!

2020-09-02 19:56 UTC, ericwbailey requested changes

2020-09-02 19:56 UTC, ericwbailey commented on src/_data/resources.json
> +			"title": "Deque Blog",
Can you move this into alphabetical order? It would be after "Blog - Karl Groves", starting on line 69.

2020-09-02 19:56 UTC, ericwbailey commented on src/_data/resources.json
> +			"description": "Free ebook: A Practical Guide to Accessible Software Development at Scale": "Dylan Barrell",
It looks like the nested quotes are breaking the build. Let's try this instead:


`"description": "Free ebook: A Practical Guide to Accessible Software Development at Scale, by Dylan Barrell.",`

2020-09-02 19:56 UTC, ericwbailey commented on src/_data/resources.json
> +			"description": "Chosen by Microsoft, Google, development and testing teams everywhere, axe is the World’s leading digital accessibility toolkit.",
Can we rephrase this to speak to what axe does, not who uses it? Right now it's unclear.

2020-09-02 19:56 UTC, ericwbailey commented on src/_data/resources.json
> +				{
Looks like the indentation here is off.

2020-09-02 19:56 UTC, ericwbailey commented on src/_data/resources.json
> +				{
Indentation is off here, as well.

2020-09-02 19:56 UTC, ericwbailey commented on src/_data/resources.json
> +			"description": "free, virtual digital accessibility conference with tracks for design, develoopers, business leaders, and compliance",
Can we capitalize the first word and add a period after the word "compliance"? We try to use full sentences for our descriptions.

2020-09-02 20:32 UTC, ljgoslin commented
@ericwbailey I've made the changes - please review again. Thanks!

2020-09-03 00:41 UTC, ericwbailey requested changes
@ljgoslin Almost there! The last, really annoying thing about JSON is if a comma is present for the last item in a list it'll break things.

2020-09-03 00:41 UTC, ericwbailey commented on src/_data/resources.json
> +				"Edge",
Remove this trailing comma.

2020-09-03 00:41 UTC, ericwbailey commented on src/_data/resources.json
> +				"Chrome",
Remove this trailing comma.

2020-09-03 14:16 UTC, ljgoslin commented
Ah gotcha, removed! I think we're good now - danke :)

2020-09-03 18:03 UTC, ericwbailey approved these changes
Woohoo! Thank you!

2020-09-03 18:04 UTC, merged