Add The A11Y Collective to resources
a11yproject/a11yproject.com pull request #1104
Opened 2020-09-10 11:38 UTC by rianrietveld

Hey, I kindly request you to add The A11Y Collective to the resources page.
We are an only e-learning platform for web accessibility at [a11y-collective.com](https://a11y-collective.com/). We are adding more courses and masterclasses each month, for everyone involved in the creation and maintenance of a web project.

2020-09-11 15:08 UTC, ericwbailey requested changes

2020-09-11 15:08 UTC, ericwbailey commented on src/_data/resources.json
> +			"title": "An e-learning platform on Web Accessibility",
Can we change this to `The A11Y Collective`? We use the name of the resource be the title.

2020-09-11 15:08 UTC, ericwbailey commented on src/_data/resources.json
> +			"additional": "The A11Y Collective",
This is an optional field, so it can be deleted if the title is updated.

2020-09-15 07:31 UTC, rianrietveld commented
Hey @ericwbailey, thanks for the review 🙂 
I changed the title and the additional.
Better this way?

2020-09-15 13:38 UTC, ericwbailey approved these changes
Looks great, thank you!

2020-09-15 13:39 UTC, merged