Adds a11ysd
a11yproject/a11yproject.com pull request #1279
Opened 2021-05-19 20:37 UTC by schne324

2021-05-20 03:22 UTC, ericwbailey requested changes
Thanks for your submission, @schne324! Would you mind moving this to be in alphabetical order to match the rest of the entries? Once that's set I'll happily merge it.

2021-05-21 04:44 UTC, schne324 commented
@ericwbailey it didn't appear that everything was quite in alphabetical order but I've placed a11ySD right before a11ySEA. Let me know if I need to move it somewhere else

2021-05-21 14:32 UTC, ericwbailey approved these changes

2021-05-21 14:32 UTC, merged

2021-05-21 14:33 UTC, ericwbailey commented
Thanks for doing that, @schne324. I'll take a look at the order as well.