Update blog, email, and professionalhelp
a11yproject/a11yproject.com pull request #1316
Opened 2021-07-26 20:09 UTC by merylke

Added A11yVR, Equal Entry blog, Equal Entry newsletter, and Equal Entry professional services.

2021-07-27 13:53 UTC, ericwbailey commented
Hi @merylke! I'm seeing some failing checks. Is that something you can take a look at, or is it something you'd like some help with? I think there's some indentation issues on line 1124.

2021-07-27 14:07 UTC, merylke commented
@ericwbailey WOW! I copied the others to be sure this wouldn't happen. I found it.

It needs a { before "title," but can't find where to edit the file. How do I do that?

		"additional": "New York, United States",
			"url": "https://www.meetup.com/a11ynyc/"
		},
			"title": "A11yVR - Accessibility Virtual Reality",
			"desc

2021-07-27 15:09 UTC, ericwbailey requested changes
I think if you accept this change it should do the trick!

2021-07-27 15:09 UTC, ericwbailey commented on src/_data/resources.json
> +			"title": "A11yVR - Accessibility Virtual Reality",
```suggestion
		},
		{
			"title": "A11yVR - Accessibility Virtual Reality",
```

2021-07-27 15:11 UTC, merylke reviewed
Looks good!

2021-07-27 15:13 UTC, merylke commented
Don't see a way to submit. I did submit for review. It would not let me "approve."

2021-07-28 14:46 UTC, ericwbailey requested changes

2021-07-28 14:46 UTC, ericwbailey commented on src/_data/resources.json
> +		},
```suggestion
		},
		{
```

2021-07-28 14:46 UTC, ericwbailey commented on src/_data/resources.json
> +		},
```suggestion
		},
		{
```

2021-07-28 14:48 UTC, ericwbailey approved these changes
@merylke In the GitHub review process the person reviewing the proposed changes is in charge of accepting or requesting changes.

I snuck in another missing opening bracket, so we should be good to merge! Thank you for submitting this.

2021-07-28 14:50 UTC, merylke commented
I'm such a Github dunce. I tried to close the pull request thinking it's all good ... but it said that it was not done yet? So sorry to make trouble!

2021-07-28 14:51 UTC, ericwbailey commented
No trouble at all! Once the checks have cleared I'll merge this code and close the Pull Request. You did the hard part of submitting the PR 🙂

2021-07-28 14:52 UTC, merged