How-to: Article how to accessible heading structure
a11yproject/a11yproject.com pull request #1391
Opened 2021-12-20 09:59 UTC by rianrietveld

Headings are the backbone of the content of a page. A visitor should be able to scan or navigate a webpage using headings to get a good impression of its content.

This PR adds a page to the posts / How-to section.

2021-12-20 15:37 UTC, ericwbailey commented
This looks incredible at a cursory skim, @rianrietveld. I'll review it tonight, but I'm very excited to see it here!

While I'm reviewing, a question for you: would you like to publish it as soon as its ready, or would you prefer to wait until holidays/New Year's Eve celebrations are over?

2021-12-21 01:03 UTC, ericwbailey requested changes
@rianrietveld This is a tour de force, and I'm so excited to have it added to our site. Thank you so much for such a comprehensive and clearly-written post!

The review comment count might look a little intimidating at first, but it's mostly suggested edits for adding newlines to make our Markdown parser happy. After that there's a few questions for you.

2021-12-21 01:03 UTC, ericwbailey commented on src/posts/how-to-accessible-heading-structure.md
> +### HeadingsMap by Jorge Rumoroso
```suggestion
### HeadingsMap by Jorge Rumoroso

```

2021-12-21 01:03 UTC, ericwbailey commented on src/posts/how-to-accessible-heading-structure.md
> +### WAVE Evaluation Tool by WebAIM
```suggestion
### WAVE Evaluation Tool by WebAIM 

```

2021-12-21 01:03 UTC, ericwbailey commented on src/posts/how-to-accessible-heading-structure.md
> +### WordPress
```suggestion
### WordPress 

```

2021-12-21 06:18 UTC, rianrietveld commented
Hey @ericwbailey, I made the changes you requested.

As for your question
> While I'm reviewing, a question for you: would you like to publish it as soon as its ready, or would you prefer to wait until holidays/New Year's Eve celebrations are over?

I leave that up to you, as long as you ping me when it's online :-)

2021-12-27 21:09 UTC, ericwbailey commented
Thanks for making the changes, @rianrietveld! I think we'll post after the start of the new year. 

Could you please [send us a message](https://www.a11yproject.com/contact/) to work out payment info and what info you'd like to use for your [author bio](https://www.a11yproject.com/authors/)?

2022-01-04 01:10 UTC, ericwbailey approved these changes

2022-01-04 01:10 UTC, merged